repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
      exclude: asv.conf.json
    - id: debug-statements
    - id: check-ast
    - id: mixed-line-ending
      args: ['--fix=no']
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    - id: pyupgrade
      args: ['--py37-plus', '--keep-runtime-typing']
  - repo: https://github.com/akaihola/darker
    rev: github-action-v1.3.2-2
    hooks:
      -   id: darker
          args: [-i]
          additional_dependencies: [isort]
