name: qcodes
channels:
 - defaults
dependencies:
 - python=3.7.9
 - pip
 - numpy=1.19.2
 - matplotlib=3.3.2
 - conda-forge::pyqtgraph=0.11.0
 - h5py=2.10.0
 - pyqt=5.9.2
 - QtPy
 - jsonschema
 - jupyter=1.0.0
 - hypothesis=6.0.0
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
 - wrapt
 - lxml
 - scipy
 - pandas
 - xarray
 - testpath>=0.4.4
 - tqdm
 - tabulate
 - pandoc
 - contextlib2 # for broadbean
 - conda-forge::websockets=8.1
 - conda-forge::schema
 - pip:
    - pyvisa==1.11.1
    - broadbean>=0.9.1
    - ruamel.yaml!=0.16.6
    - opencensus-ext-azure
