name: qcodes
channels: 
 - defaults
 - conda-forge
dependencies:
 - h5py=2.6.0
 - matplotlib=2.0.2
 - pyqtgraph 
 - python=3.6
 - jsonschema
 - pyvisa
 - QtPy=1.2.0
 - sip
 - pyqt=5.6.0
 - numpy
 - jupyter=1.0.0
 - typing
 - hypothesis
 - pytest
 - pytest-runner