name: qcodes
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3.6.8
 - pip
 - numpy=1.16.4 # numpy 1.16.0 .. 1.16.2 may fail our tests due to https://github.com/numpy/numpy/issues/13089
 - matplotlib=3.1
 - pyqtgraph=0.10.0
 - pyvisa=1.9.1
 - h5py=2.9.0
 - pyqt=5.9
 - QtPy
 - jsonschema
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
 - ruamel_yaml
 - wrapt
 - pyyaml
 - lxml
 - scipy
 - gitpython
 - pandas
 - testpath>=0.4.2 # 0.4.1 is bad due to https://github.com/conda-forge/testpath-feedstock/issues/7
 - tqdm
 - gitpython
 - dataclasses  # this won't be needed when we move to python 3.7
 - tabulate
 - pip:
    - websockets>=7.0
    - broadbean>=0.9.1
    - ruamel.yaml
