name: qcodes
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3.6.6 # Currently there is a problem with 3.6.7 and matplotlib 3.0.0 on conda
 - numpy=1.15
 - matplotlib=3.0.0
 - pyqtgraph=0.10.0
 - pyvisa=1.9.1
 - h5py=2.8.0
 - pyqt=5.9
 - QtPy
 - jsonschema
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
 - wrapt
 - pyyaml
 - lxml
 - scipy
 - ruamel_yaml
 - gitpython
 - pandas
 - testpath>=0.4.2 # 0.4.1 is bad due to https://github.com/conda-forge/testpath-feedstock/issues/7
 - tqdm
 - pip:
    - websockets>=3.2
    - broadbean>=0.9.1
