name: qcodes
channels:
 - defaults
 - conda-forge
dependencies:
 - python=3.6
 - numpy=1.15
 - matplotlib=3.0.0
 - pyqtgraph=0.10.0
 - pyvisa=1.9.1
 - h5py=2.8.0
 - pyqt=5.9
 - QtPy
 - jsonschema
 - jupyter=1.0.0
 - hypothesis
 - pytest
 - pytest-runner
 - spyder
 - pyzmq
 - wrapt
 - pyyaml
 - lxml
 - scipy
 - ruamel_yaml
 - pip:
    - websockets>=3.2
    - broadbean>=0.9.1
